'use client'
import { Inter, Jost } from "next/font/google";
import "./globals.css";
import { Providers } from "./GlobalRedux/provider";
import GeneralFunctions from "./GeneralFunctions";
import { useEffect } from "react";

const jost = Jost({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }; 

export default function RootLayout({ children }) {
  useEffect(() => {
    console.log('You are welcome.')
  }, [])
  return (
    // className={jost.className}
    <html lang="en" suppressHydrationWarning>
      <body >
        <Providers>
          <GeneralFunctions>{children}</GeneralFunctions>
        </Providers>
      </body>
    </html>
  );
}
